### ISSUE TITLE
collect POART reviews or similar internal review docs

### ISSUE THREAD

**Issue by jessmhoehner** [USAID-OHA-SI/project_arachne#3]
- [x] request POART reviews from team during next call
- [ ] identify where gaps exist in availability or POART reviews and which documents can/should be used instead

**Comment by achafetz** [comment]
I reached out to Emily R to see if SCC had a repository for POARTs. 

> We don’t have them all in a single folder, but there are a couple of places where poart decks are kept on the OHA shared drive. 
> 
> 1) maybe more comprehensive - each OU Cluster folder should have slides saved (
> https://drive.google.com/drive/folders/1jOaqO2rE4Wajuupqxb46aq8hP6fSqUZx)
> 
> 2) for some quarters, we did keep files centrally in a poart folder. We just haven’t done this every single quarter. (
> https://drive.google.com/drive/folders/17XMIITNIiWCCiC0c3-oFiPLJ_YXK2AmG)
